[package]
name = "forge_main_neo"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
color-eyre = "0.6.3"
crossterm = "0.29.0"
forge_api.workspace = true
ratatui = "0.29.0"
tokio.workspace = true
tui-textarea = "0.7.0"
derive_more.workspace = true
