version: '3.8'

services:
  vector-db:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-storage:/qdrant/storage
    environment:
      - QDRANT_API_KEY=your_api_key_here
    
  indexer:
    build:
      context: .
      dockerfile: Dockerfile.indexer
    depends_on:
      - vector-db
      - nats
    environment:
      - VECTOR_DB_URL=http://vector-db:6333
      - NATS_URL=nats://nats:4222
      - EMBEDDING_PROVIDER=openai
      - OPENAI_API_KEY=your_openai_key_here
    volumes:
      - .:/workspace
    
  retrieval-api:
    build:
      context: .
      dockerfile: Dockerfile.retrieval
    depends_on:
      - vector-db
      - nats
    ports:
      - "8080:8080"
    environment:
      - VECTOR_DB_URL=http://vector-db:6333
      - NATS_URL=nats://nats:4222
      - EMBEDDING_PROVIDER=openai
      - OPENAI_API_KEY=your_openai_key_here
      
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js"]
    
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    
volumes:
  qdrant-storage:
  grafana-storage:
  prometheus-storage:
