[package]
name = "forge_fs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
anyhow.workspace = true
chrono = { version = "0.4", default-features = false, features = ["clock"] }
rand = "0.8.5"