[package]
name = "forge_review"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros", "time"] }

[features]
default = ["time", "futures"]
time = []
futures = []
