[package]
name = "forge_review"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
forge_api.workspace = true
futures.workspace = true
tempfile.workspace = true
forge_fs.workspace = true
schemars.workspace = true
serde.workspace = true
