[package]
name = "forge_infra"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
async-trait = "0.1.86"
dirs = "6.0.0"
dotenv = "0.15.0"
forge_domain = { path = "../forge_domain" }
forge_app = { path = "../forge_app" }
tokio = "1.43.0"
serde_json = "1.0.138"
qdrant-client = "1.13.0"
rust-bert = {version="0.23.0", default-features = false, features = ["rustls-tls", "remote"]}
