name: Release Drafter
on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
  push:
    branches:
    - main
jobs:
  update_release_draft:
    name: update_release_draft
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: release-drafter/release-drafter@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
