name: ✨ Feature Request
description: Suggest a new feature or enhancement for Forge
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information to help us understand your proposal.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe the problem you're trying to solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like Forge to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've also thought about...

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used.
      placeholder: |
        1. As a developer, I want to...
        2. When working on large projects, I need to...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - AI/LLM Integration
        - Code Generation/Editing
        - File Operations
        - Configuration
        - CLI/UX
        - Documentation
        - Performance
        - Security
        - MCP Integration
        - Multi-Agent Workflows
        - Shell Plugin
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority/Impact
      description: How important is this feature to your workflow?
      options:
        - Critical - Blocking my work
        - High - Would significantly improve my workflow
        - Medium - Would be nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples from Other Tools
      description: Are there similar features in other tools that could serve as inspiration?
      placeholder: Tool X does this by...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have any ideas about how this could be implemented, share them here.
      placeholder: This could be implemented by...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'm willing to submit a PR to implement this feature
        - label: I can help with testing
        - label: I can help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
