[package]
name = "forge"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
forge_api = { path = "../forge_api" }
forge_app = { path = "../forge_app" }
forge_walker = { path = "../forge_walker" }
forge_display = { path = "../forge_display" }
forge_tracker = { path = "../forge_tracker" }
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1.17"
colored = "3.0.0"
crossterm = { version = "0.28", features = ["event-stream"] }
async-trait = "0.1"
regex = "1.10.2"
strum = { version = "0.27", features = ["derive"] }
anyhow = "1.0.95"
chrono = "0.4"
derive_setters = "0.1"
lazy_static = "1.4.0"
serde_json = "1.0"
thiserror = "2.0"
reedline = "0.38.0"
nu-ansi-term = "0.50.1"
dirs = "6.0.0"
tracing = "0.1.41"

[dev-dependencies]
insta = "1.34.0"
once_cell = "1.19.0"
pretty_assertions = "1.4.1"
tempfile = "3.9.0"
