[package]
name = "forge_main"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
forge_server = { path = "../forge_server" }
forge_domain = { path = "../forge_domain" }
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1.17"
colored = "3.0.0"
inquire = "0.7.5"
unicode-width = "0.2.0"
regex = "1.10.2"
strum = "0.26.3"
strum_macros = "0.26.4"
anyhow = "1.0.95"

[dev-dependencies]
insta = "1.34.0"
once_cell = "1.19.0"
