[package]
name = "forge_buffer"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tokio.workspace = true
futures.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
tempfile.workspace = true
