[package]
name = "forge_snapshot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
sha2 = "0.9"
async-trait = "0.1"
chrono = "0.4.39"
serde = { version = "1.0" }

