[package]
name = "forge_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
dissimilar = "1.0"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
async-trait = "0.1"
url = { version = "2.5", features = ["serde"] }
tracing = "0.1"
colorize = "0.1.0"
Inflector = "0.11.4"
forge_tool_macros = { path = "../forge_tool_macros" }
schemars = "0.8.21"
regex = "1.10.2"
walkdir = "2.4.0"
glob = "0.3.1"
tree-sitter = "0.24.0"
tree-sitter-rust = "0.20.4"
tree-sitter-javascript = "0.20.1"
tree-sitter-python = "0.20.4"
replace_with = "0.1.7"
forge_walker = { path = "../forge_walker" }

tempfile = "3.8.1"
handlebars = "6.2.0"

[dev-dependencies]
insta = "1.34.0"
