[package]
name = "forge_evals"
version = "0.1.0"
edition = "2024"

[dependencies]
forge_domain.workspace = true
serde_json.workspace = true
anyhow.workspace = true
regex.workspace = true

[dev-dependencies]
pretty_assertions = "1.4"
