[package]
name = "forge_treesitter"
version = "0.1.0"
edition = "2024"

[dependencies]
tree-sitter.workspace = true
tree-sitter-rust.workspace = true
thiserror.workspace = true
anyhow.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
insta.workspace = true