[package]
name = "forge_attachments"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
forge_domain = {path = "../forge_domain"}
base64 = "0.22.1"
tokio = {version = "1.43.0", features = ["fs"]}
