[package]
name = "forge_ci"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
gh-workflow-tailcall.workspace = true
pretty_assertions.workspace = true
serde_json.workspace = true
indexmap.workspace = true