[package]
name = "forge_stream"
version = "0.1.0"
edition = "2024"

[dependencies]
futures.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "time", "test-util"] }