# Forge PowerShell Plugin - Main Loader
# This file is generated by `forge powershell plugin` and should not be edited.
# Sources all forge plugin modules in the correct order.

# The individual module contents are concatenated here by the Rust plugin
# generator. This file serves as the template/entry point.
